### ISSUE TITLE
Git push fails with - npm does not support Node.js v8.17.0

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/sphereio-component#114]
```
-----> Elastic.io Node.js component app detected
-----> Compiling buildpack...
       Build root dir: /tmp/build
       Cache root dir: /tmp/cache

-----> Reading application state
       package.json...
       build directory...
       cache directory...
       environment variables...

       Node engine:         ^8.4.0
       Npm engine:          >=5.4
       Start mechanism:     none
       node_modules source: package.json
       node_modules cached: false

       NPM_CONFIG_PRODUCTION=false
       NODE_MODULES_CACHE=true

-----> Installing binaries
       Resolving node version ^8.4.0 via semver.io...
       Downloading and installing node 8.17.0...
       Resolving npm version >=5.4 via semver.io...
       Downloading and installing npm  (replacing version 6.13.4)...
       npm WARN notsup Unsupported engine for npm@8.3.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"8.17.0","npm":"6.13.4"})
       npm WARN notsup Not compatible with your version of node/npm: npm@8.3.0

remote: npm does not support Node.js v8.17.0
remote: You should probably upgrade to a newer version of node as we
remote: can't make any promises that npm will work with this version.
remote: You can find the latest version at https://nodejs.org/
remote: /tmp/build/.heroku/node/lib/node_modules/npm/lib/npm.js:32
remote:   #unloaded = false
remote:   ^
remote:
remote: SyntaxError: Invalid or unexpected token
remote:     at createScript (vm.js:80:10)
remote:     at Object.runInThisContext (vm.js:139:10)
remote:     at Module._compile (module.js:617:28)
remote:     at Object.Module._extensions..js (module.js:664:10)
remote:     at Module.load (module.js:566:32)
remote:     at tryModuleLoad (module.js:506:12)
remote:     at Function.Module._load (module.js:498:3)
remote:     at Module.require (module.js:597:17)
remote:     at require (internal/module.js:11:18)
remote:     at module.exports (/tmp/build/.heroku/node/lib/node_modules/npm/lib/cli.js:22:15)
remote: /tmp/buildpacks/elasticio-buildpack-nodejs#ac63018/lib/warnings.sh: line 30: [: -: integer expression expected

-----> Building dependencies
       Disabling Certificate Authority by NPM
remote: npm does not support Node.js v8.17.0
remote: You should probably upgrade to a newer version of node as we
remote: can't make any promises that npm will work with this version.
remote: You can find the latest version at https://nodejs.org/
remote: /tmp/build/.heroku/node/lib/node_modules/npm/lib/npm.js:32
remote:   #unloaded = false
remote:   ^
remote:
remote: SyntaxError: Invalid or unexpected token
remote:     at createScript (vm.js:80:10)
remote:     at Object.runInThisContext (vm.js:139:10)
remote:     at Module._compile (module.js:617:28)
remote:     at Object.Module._extensions..js (module.js:664:10)
remote:     at Module.load (module.js:566:32)
remote:     at tryModuleLoad (module.js:506:12)
remote:     at Function.Module._load (module.js:498:3)
remote:     at Module.require (module.js:597:17)
remote:     at require (internal/module.js:11:18)
remote:     at module.exports (/tmp/build/.heroku/node/lib/node_modules/npm/lib/cli.js:22:15)

-----> Build failed

       We're sorry this build is failing! If you can't find the issue in component code,
       please submit a ticket so we can help: https://support.elastic.io
       You can also try upgrading Sailor to the most recent version. Check out
       https://www.npmjs.com/package/elasticio-sailor-nodejs

       Your elastic.io team
remote:
remote: Detaching from log stream
remote: Removing slug.
remote: Build failed
remote: Error: Build pod failed
remote: Error: Build pod failed
remote:     at onUpdate (/home/node/gitreceiver/src/lib/builder.js:122:31)
remote:     at /home/node/gitreceiver/node_modules/@kubernetes/client-node/dist/cache.js:185:49
remote:     at Array.forEach (<anonymous>)
remote:     at addOrUpdateObject (/home/node/gitreceiver/node_modules/@kubernetes/client-node/dist/cache.js:185:32)
remote:     at ListWatch.watchHandler (/home/node/gitreceiver/node_modules/@kubernetes/client-node/dist/cache.js:135:17)
remote:     at LineStream.<anonymous> (/home/node/gitreceiver/node_modules/@kubernetes/client-node/dist/watch.js:87:21)
remote:     at LineStream.emit (events.js:314:20)
remote:     at addChunk (_stream_readable.js:298:12)
remote:     at readableAddChunk (_stream_readable.js:273:9)
remote:     at LineStream.Readable.push (_stream_readable.js:214:10)
remote:     at LineStream.Transform.push (_stream_transform.js:152:32)
remote:     at LineStream._pushBuffer (/home/node/gitreceiver/node_modules/byline/lib/byline.js:126:17)
remote:     at LineStream._transform (/home/node/gitreceiver/node_modules/byline/lib/byline.js:117:8)
remote:     at LineStream.Transform._read (_stream_transform.js:191:10)
remote:     at LineStream.Transform._write (_stream_transform.js:179:12)
remote:     at doWrite (_stream_writable.js:403:12)
remote:     at writeOrBuffer (_stream_writable.js:387:5)
remote:     at LineStream.Writable.write (_stream_writable.js:318:11)
remote:     at Request.ondata (internal/streams/legacy.js:19:31)
remote:     at Request.emit (events.js:314:20)
remote:     at IncomingMessage.<anonymous> (/home/node/gitreceiver/node_modules/request/request.js:1080:12)
remote:     at IncomingMessage.emit (events.js:314:20)
remote:     at addChunk (_stream_readable.js:298:12)
remote:     at readableAddChunk (_stream_readable.js:273:9)
remote:     at IncomingMessage.Readable.push (_stream_readable.js:214:10)
remote:     at HTTPParser.parserOnBody (_http_common.js:135:24)
remote:     at TLSSocket.socketOnData (_http_client.js:475:22)
remote:     at TLSSocket.emit (events.js:314:20)
remote:     at addChunk (_stream_readable.js:298:12)
remote:     at readableAddChunk (_stream_readable.js:273:9)
remote:     at TLSSocket.Readable.push (_stream_readable.js:214:10)
remote:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
remote: {"name":"gitreceiver","hostname":"gitreceiver-84dfd954b8-trppv","pid":"2576","level":"50","error":{},"msg":"","time":"2021-12-15T15:45:01.169Z","v":"0"}
To haufe:sphereio.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'haufe:sphereio.git'
```

**Comment by khanzadyan** [comment]
@A3a3e1 and @jhorbulyk FYI
